select * from T_SAL_DELIVERYNOTICE where FBILLNO like '%DH%'

delete  from T_SAL_DELIVERYNOTICE where FBILLNO like '%DH%'

select * from T_SAL_DELIVERYNOTICEENTRY where FDELIVERYDATE = '2016-11-1' and FDELIVERYADDRESS = '安宁金牛街海龙数码广场VIVO专卖店（张炜炜）'

delete  from T_SAL_DELIVERYNOTICEENTRY where FDELIVERYDATE = '2016-11-1' and FDELIVERYADDRESS = '安宁金牛街海龙数码广场VIVO专卖店（张炜炜）'

select * from T_SAL_DELIVERYNOTICEENTRY_E where FENTRYID = 1878851

delete  from T_SAL_DELIVERYNOTICEENTRY_E where FENTRYID = 1878851

select * from T_SAL_DELIVERYNOTICEENTRY_F where FENTRYID = 1878852

delete  from T_SAL_DELIVERYNOTICEENTRY_F where FENTRYID = 1878852

select * from T_SAL_DELIVERYNOTICEFIN where FENTRYID = 1878852

delete  from T_SAL_DELIVERYNOTICEFIN where FENTRYID = 1878852