USE [AIS20161110162318]
GO

INSERT INTO [dbo].[T_SAL_ORDERENTRY]
           ([FENTRYID]
           ,[FID]
           ,[FSEQ]
           ,[FMATERIALID]
           ,[FAUXPROPID]
           ,[FBOMID]
           ,[FUNITID]
           ,[FQTY]
           ,[FBASEUNITID]
           ,[FBASEUNITQTY]
           ,[FMRPFREEZESTATUS]
           ,[FFREEZEDATE]
           ,[FFREEZERID]
           ,[FMRPTERMINATESTATUS]
           ,[FTERMINATERID]
           ,[FTERMINATEDATE]
           ,[FMRPCLOSESTATUS]
           ,[FLOT]
           ,[FSTOCKORGID]
           ,[FSTOCKID]
           ,[FLOCKQTY]
           ,[FLOCKFLAG]
           ,[FOWNERTYPEID]
           ,[FOWNERID]
           ,[FPRODUCEDATE]
           ,[FEXPIRYDATE]
           ,[FEXPPERIOD]
           ,[FPRIORITY]
           ,[FRESERVETYPE]
           ,[FPLANDELIVERYDATE]
           ,[FDELIVERYSTATUS]
           ,[FOLDQTY]
           ,[FSUPPLYORGID]
           ,[FNETORDERENTRYID]
           ,[FSTOCKUNITID]
           ,[FSTOCKQTY]
           ,[FSTOCKBASEQTY]
           ,[F_PAEZ_STOCK]
           ,[FLEFTQTY])
     VALUES
           (400976
           ,237049
           ,1
           ,152888
           ,0
           ,0
           ,106017
           ,10
           ,106017
           ,10
           ,'A'
           ,NULL
           ,0
           ,'A'
           ,0
           ,NULL
           ,'A'
           ,0
           ,104772
           ,0
           ,0
           ,0
           ,'BD_OwnerOrg'
           ,104772
           ,NULL
           ,NULL
           ,0
           ,0
           ,1
           ,'2017-1-3'
           ,'A'
           ,10
           ,104772
           ,0
           ,106017
           ,10
           ,10
           ,0
           ,0)
GO


