USE [AIS20161110162318]
GO

INSERT INTO [dbo].[T_SAL_ORDER]
           ([FID]
           ,[FBILLTYPEID]
           ,[FBILLNO]
           ,[FDATE]
           ,[FCUSTID]
           ,[FSALEORGID]
           ,[FSALEGROUPID]
           ,[FSALEDEPTID]
           ,[FSALERID]
           ,[FCREATORID]
           ,[FCREATEDATE]
           ,[FMODIFIERID]
           ,[FMODIFYDATE]
           ,[FDOCUMENTSTATUS]
           ,[FAPPROVERID]
           ,[FAPPROVEDATE]
           ,[FCLOSESTATUS]
           ,[FCLOSERID]
           ,[FCLOSEDATE]
           ,[FCANCELSTATUS]
           ,[FCANCELLERID]
           ,[FCANCELDATE]
           ,[FRECEIVEID]
           ,[FSETTLEID]
           ,[FCHARGEID]
           ,[FVERSIONNO]
           ,[FCHANGEDATE]
           ,[FCHANGERID]
           ,[FBUSINESSTYPE]
           ,[FHEADLOCID]
           ,[FCREDITCHECKRESULT]
           ,[FOBJECTTYPEID]
           ,[FFINALVERSION]
           ,[FORIGINALFID]
           ,[FCORRESPONDORGID]
           ,[FRECCONTACTID]
           ,[FNETORDERBILLID]
           ,[FISINIT]
           ,[FOPPID]
           ,[FSALEPHASEID])
     VALUES
           (237049
           ,(select cast(NEWID() as varchar(36)) as uuid)
           ,'XD15011701000002'
           ,'2017-1-3'
           ,'109208'
           ,'104772'
		   ,'108166'
           ,'104795'
           ,'216897'
           ,'141242'
           ,'2017-1-3'
           ,'141242'
           ,'2017-1-3'
           ,'A'
           ,0
           ,NULL
           ,'A'
           ,0
           ,NULL
           ,'A'
           ,0
           ,NULL
           ,109208
           ,109208
           ,109208
           ,000
           ,NULL
           ,0
           ,'NORMAL'
           ,0
           ,0
           ,'SAL_SaleOrder'
           ,1
           ,0
           ,104774
           ,0
           ,0
           ,0
           ,0
           ,0)
GO


