insert bulk T_SAL_DELIVERYNOTICE (
	[FID] Int, [FBILLTYPEID] VarChar(36) COLLATE Chinese_PRC_CI_AS, [FBILLNO] NVarChar(30) COLLATE Chinese_PRC_CI_AS, 
	[FDATE] DateTime, [FCUSTOMERID] Int, [FDELIVERYORGID] Int, [FDELIVERYDEPTID] Int, [FSTOCKERGROUPID] Int, [FSTOCKERID] Int, 
	[FRECEIVERID] Int, [FSETTLEID] Int, [FPAYERID] Int, [FCARRIAGENO] NVarChar(30) COLLATE Chinese_PRC_CI_AS, [FCARRIERID] Int, 
	[FSALEORGID] Int, [FSALEGROUPID] Int, [FSALEDEPTID] Int, [FSALESMANID] Int, [FNOTE] NVarChar(255) COLLATE Chinese_PRC_CI_AS, 
	[FDOCUMENTSTATUS] Char(1) COLLATE Chinese_PRC_CI_AS, [FCANCELSTATUS] Char(1) COLLATE Chinese_PRC_CI_AS, [FCREATORID] Int, 
	[FCREATEDATE] DateTime, [FMODIFIERID] Int, [FMODIFYDATE] DateTime, [FAPPROVERID] Int, [FAPPROVEDATE] DateTime, [FCANCELLERID] Int, 
	[FCANCELDATE] DateTime, [FOWNERTYPEID] VarChar(36) COLLATE Chinese_PRC_CI_AS, [FOWNERID] Int, [FCLOSERID] Int, [FCLOSEDATE] DateTime, 
	[FCLOSESTATUS] Char(1) COLLATE Chinese_PRC_CI_AS, [FRECEIPTCONDITIONID] Int, [FHEADLOCID] Int, 
	[FHEADDELIVERYWAY] VarChar(36) COLLATE Chinese_PRC_CI_AS, [FISSYSCLOSE] Char(1) COLLATE Chinese_PRC_CI_AS, 
	[FBUSINESSTYPE] VarChar(20) COLLATE Chinese_PRC_CI_AS, [FRECEIVEADDRESS] NVarChar(255) COLLATE Chinese_PRC_CI_AS, 
	[FCREDITCHECKRESULT] Char(1) COLLATE Chinese_PRC_CI_AS, [FOBJECTTYPEID] VarChar(36) COLLATE Chinese_PRC_CI_AS, [FCORRESPONDORGID] Int, 
	[FRECCONTACTID] Int)





insert bulk T_SAL_DELIVERYNOTICEENTRY (
	[FENTRYID] Int, [FID] Int, [FSEQ] Int, [FCUSTMATID] NVarChar(30) COLLATE Chinese_PRC_CI_AS, [FMATERIALID] Int, [FAUXPROPID] Int, 
	[FUNITID] Int, [FQTY] Decimal(23,10), [FSHIPMENTSTOCKID] Int, [FSHIPMENTSTOCKLOCID] Int, [FDELIVERYLOC] Int, 
	[FDELIVERYADDRESS] NVarChar(255) COLLATE Chinese_PRC_CI_AS, [FDELIVERYDATE] DateTime, [FPLANDELIVERYDATE] DateTime, 
	[FCARRYLEADTIME] Int, [FBOMID] Int, [FLOT] Int, [FLOT_TEXT] NVarChar(255) COLLATE Chinese_PRC_CI_AS, [FBASEUNITID] Int, 
	[FBASEUNITQTY] Decimal(23,10), [FOUTCONTROL] Char(1) COLLATE Chinese_PRC_CI_AS, [FOUTMAXQTY] Decimal(23,10), 
	[FOUTMINQTY] Decimal(23,10), [FSRCTYPE] VarChar(36) COLLATE Chinese_PRC_CI_AS, [FSRCBILLNO] NVarChar(160) COLLATE Chinese_PRC_CI_AS, 
	[FNOTE] NVarChar(255) COLLATE Chinese_PRC_CI_AS, [FJOINOUTQTY] Decimal(23,10), [FBASEJOINOUTQTY] Decimal(23,10), 
	[FSUMOUTQTY] Decimal(23,10), [FORDERNO] NVarChar(160) COLLATE Chinese_PRC_CI_AS, [FORDERSEQ] NVarChar(100) COLLATE Chinese_PRC_CI_AS, 
	[FBACKUPSTOCKID] Int, [FBACKUPSTOCKLOCID] Int, [FTRANSFERQTY] Decimal(23,10), [FBASETRANSFERQTY] Decimal(23,10), 
	[FBASESUMOUTQTY] Decimal(23,10), [FPRODUCEDATE] DateTime, [FEXPPERIOD] Decimal(19,6), [FEXPIRYDATE] DateTime, 
	[FREMAINOUTQTY] Decimal(23,10), [FCLOSESTATUS] Char(1) COLLATE Chinese_PRC_CI_AS, [FSTOCKSTATUSID] Int, 
	[FBASEOUTMAXQTY] Decimal(23,10), [FBASEOUTMINQTY] Decimal(23,10), [FBFLOWID] VarChar(36) COLLATE Chinese_PRC_CI_AS, 
	[FMTONO] NVarChar(255) COLLATE Chinese_PRC_CI_AS)



insert bulk T_SAL_DELIVERYNOTICEFIN (
	[FENTRYID] Int, [FID] Int, [FSETTLEORGID] Int, [FSETTLETYPEID] Int, [FSETTLECURRID] Int, [FLOCALCURRID] Int, [FEXCHANGETYPEID] Int, 
	[FEXCHANGERATE] Decimal(19,6), [FPRICELISTID] Int, [FDISCOUNTLISTID] Int, [FBILLTAXAMOUNT] Decimal(23,10), 
	[FBILLTAXAMOUNT_LC] Decimal(23,10), [FBILLAMOUNT] Decimal(23,10), [FBILLAMOUNT_LC] Decimal(23,10), [FBILLALLAMOUNT] Decimal(23,10), 
	[FBILLALLAMOUNT_LC] Decimal(23,10), [FISINCLUDEDTAX] Char(1) COLLATE Chinese_PRC_CI_AS, 
	[FCRECHKSTATUS] Char(1) COLLATE Chinese_PRC_CI_AS, [FCRECHKAMOUNT] Decimal(23,10), [FCRECHKDAYS] Int)




insert bulk T_SAL_DELIVERYNOTICEENTRY_F (
	[FENTRYID] Int, [FID] Int, [FPRICEUNITID] Int, [FPRICEUNITQTY] Decimal(23,10), [FPRICE] Decimal(23,10), [FTAXPRICE] Decimal(23,10), 
	[FTAXRATE] Decimal(19,6), [FPRICECOEFFICIENT] Decimal(19,6), [FSYSPRICE] Decimal(23,10), [FLIMITDOWNPRICE] Decimal(23,10), 
	[FBEFDISAMT] Decimal(23,10), [FBEFDISALLAMT] Decimal(23,10), [FDISCOUNTRATE] Decimal(19,6), [FDISCOUNT] Decimal(23,10), 
	[FTAXNETPRICE] Decimal(23,10), [FAMOUNT] Decimal(23,10), [FAMOUNT_LC] Decimal(23,10), [FTAXAMOUNT] Decimal(23,10), 
	[FTAXAMOUNT_LC] Decimal(23,10), [FALLAMOUNT] Decimal(23,10), [FALLAMOUNT_LC] Decimal(23,10), [FISFREE] Char(1) COLLATE Chinese_PRC_CI_AS, 
	[FTAXCOMBINATION] Int, [FPRICEBASEQTY] Decimal(23,10), [FSALBASENUM] Decimal(23,10), [FSTOCKBASEDEN] Decimal(23,10), [FSRCBIZUNITID] Int)



insert bulk T_SAL_DELIVERYNOTICEENTRY_E (
	[FENTRYID] Int, [FID] Int, [FTERMINATERID] Int, [FTERMINATEDATE] DateTime, [FTERMINATIONSTATUS] Char(1) COLLATE Chinese_PRC_CI_AS, 
	[FOWNERTYPEID] VarChar(36) COLLATE Chinese_PRC_CI_AS, [FOWNERID] Int, [FQUALIFIEDQTY] Decimal(23,10), [FBASEQUALIFIEDQTY] Decimal(23,10), 
	[FUNQUALIFIEDQTY] Decimal(23,10), [FBASEUNQUALIFIEDQTY] Decimal(23,10), [FJUNKEDQTY] Decimal(23,10), [FBASEJUNKEDQTY] Decimal(23,10), 
	[FSTOCKUNITID] Int, [FSTOCKQTY] Decimal(23,10), [FSTOCKBASEQTY] Decimal(23,10), [FSTOCKBASEJOINOUTQTY] Decimal(23,10), 
	[FSTOCKBASESUMOUTQTY] Decimal(23,10), [FSTOCKBASETRANSQTY] Decimal(23,10), [FBASEJOINQUALIFIEDQTY] Decimal(23,10), 
	[FJOINQUALIFIEDQTY] Decimal(23,10), [FBASEJOINUNQUALIFIEDQTY] Decimal(23,10), [FJOINUNQUALIFIEDQTY] Decimal(23,10), 
	[FBASEUQCANSALEQTY] Decimal(23,10), [FUQCANSALEQTY] Decimal(23,10), [FBASEJOINCHECKQTY] Decimal(23,10), [FJOINCHECKQTY] Decimal(23,10), 
	[FJOINDELICHKQTY] Decimal(23,10), [FBASEJOINDELICHKQTY] Decimal(23,10), [FJOINDELICHKUQQTY] Decimal(23,10), 
	[FBASEJOINDELICHKUQQTY] Decimal(23,10), [FDELICHKTRANOUTQTY] Decimal(23,10), [FBASEDELICHKTRANOUTQTY] Decimal(23,10), 
	[FDELICHKTRANOUTUQQTY] Decimal(23,10), [FBASEDELICHKTRANOUTUQQTY] Decimal(23,10), [FOUTLMTUNIT] VarChar(10) COLLATE Chinese_PRC_CI_AS, 
	[FOUTLMTUNITID] Int, [FSOENTRYID] Int, [FTRANSRETURNQTY] Decimal(23,10), [FTRANSRETURNBASEQTY] Decimal(23,10), 
	[FCONSIGNSETTQTY] Decimal(23,10), [FCONSIGNSETTBASEQTY] Decimal(23,10))





insert bulk T_SAL_DELIVERYNOTICEENTRYTAX (
	[FDETAILID] Int, [FENTRYID] Int, [FSEQ] Int, [FTAXRATEID] Int, [FTAXRATE] Decimal(23,10), [FTAXAMOUNT] Decimal(23,10), 
	[FCOSTPERCENT] Decimal(23,10), [FVAT] Char(1) COLLATE Chinese_PRC_CI_AS, [FSELLERWITHHOLDING] Char(1) COLLATE Chinese_PRC_CI_AS, 
	[FBUYERWITHHOLDING] Char(1) COLLATE Chinese_PRC_CI_AS, [FCOSTAMOUNT] Decimal(23,10))




insert bulk T_BAS_OPERATELOG (
	[FID] VarChar(36) COLLATE Chinese_PRC_CI_AS, [FUSERID] Int, [FBIZORGID] Int, [FLOGONORGID] Int, [FDATETIME] DateTime, 
	[FSUBSYSTEMID] VarChar(36) COLLATE Chinese_PRC_CI_AS, [FCOMPUTERNAME] NVarChar(100) COLLATE Chinese_PRC_CI_AS, 
	[FIPADDRESS] NVarChar(100) COLLATE Chinese_PRC_CI_AS, [FDESCRIPTION] NVarChar(2000) COLLATE Chinese_PRC_CI_AS, 
	[FENVIRONMENT] Char(1) COLLATE Chinese_PRC_CI_AS, [FOBJECTTYPEID] VarChar(255) COLLATE Chinese_PRC_CI_AS, 
	[FOPERATENAME] NVarChar(50) COLLATE Chinese_PRC_CI_AS) with (CHECK_CONSTRAINTS)



INSERT INTO T_BAS_NETWORKCTRLRECORDS (
	FID, FTOKEN, FNETCTRLID, FINTERID, FSTATION, FIP, FOPERATIONDESC, FUSERID, FEXECUTIVEORG, FNETCTRLTYPE, FDETAILFUNCID, FTIME
	) 
	VALUES (
	'ec8f87cb-fc6e-8117-11e6-abcf477c0472','c4d29fba-ffe6-41a3-a5da-0d0e8a01e836','e050af6d9c624d3390613df68a908be2',N'473451',
	N'HCTBBK',N'114.55.93.161(MAC:00:16:3E:00:1F:14)>GATE:fe80::6d41:b713:2fd9:427d%20',N'发货通知单-T15011611004653-修改',
	141240,104772,6,N'修改','2016-11-16 15:35:48.917'
	)



